../../../RTL/Debug/LocalMon.v
../../../RTL/Debug/BPProbe.v
../../../RTL/Debug/SProbe.v
../../../RTL/Debug/DBusProbe.v
../../../RTL/Debug/IBusProbe.v
../../../RTL/Debug/PCtrl.v
../../../RTL/Debug/TCProbe.v
../../../RTL/Debug/WPProbe.v
../../../RTL/Debug/jtag.v
../../../RTL/Debug/MMProbe.v
../../../RTL/Debug/LocalOCD.v
../../../RTL/Debug/RegProbe.v
../../../RTL/Debug/RFProbe.v
../../../RTL/Debug/DAP.v
../../../RTL/Debug/UploadFSM.v
../../../RTL/Debug/CmdExeFSM.v
../../../RTL/APE/RFM.v
../../../RTL/SPU/SEQ.v
../../../RTL/SPU/SCU.v
../../../RTL/SPU/SEQSend.v
../../../RTL/SPU/Fetch.v
../../../RTL/SPU/Decode.v
../../../RTL/SPU/SYN.v
../../../RTL/SPU/SCUBasicEx1.v
../../../RTL/SPU/AGU.v
../../../RTL/SPU/SPUPipeCtrl.v
../../../RTL/SPU/SPU.v
../../../RTL/SPU/SCUBasicEx0.v
../../../RTL/SPU/RRegFile.v
../../../RTL/MPU/MPU.v
../../../RTL/MPU/WaitMemory.v
../../../RTL/MPU/DPath.v
../../../RTL/MPU/IMA/ALUEx1.v
../../../RTL/ASSIST/Arbiter.v
../../../RTL/MPU/IMA/ByteOr.v
../../../RTL/MPU/IMA/IMABasicEX0.v
../../../RTL/MPU/IMA/IMABasicEX1.v
../../../RTL/MPU/IMA/IMABasicEX2.v
../../../RTL/MPU/IMA/CLZ_g32.v
../../../RTL/MPU/IMA/BIT_PICK_8.v
../../../RTL/MPU/IMA/IMAMulSel.v
../../../RTL/MPU/IMA/IMA.v
../../../RTL/MPU/IMA/Index.v
../../../RTL/MPU/IMA/TReg_w6_r4_v6_ForIMAC.v
../../../RTL/MPU/IMA/TurboPre.v
../../../RTL/MPU/MFetch.v
../../../RTL/MPU/MReg/MRegUnit.v
../../../RTL/MPU/MReg/RegFile.v
../../../RTL/MPU/MReg/MRegCtrl.v
../../../RTL/MPU/SHU.v
../../../RTL/MPU/TReg_w8_r3_v8.v
../../../RTL/MPU/Turbo.v
../../../RTL/MPU/SCompBS.v
../../../RTL/MPU/DW01_cmp2.v
../../../RTL/MPU/DW01_decode.v
../../../RTL/MPU/BIU.v
../../../RTL/MPU/DPathIndex.v
../../../RTL/DBus/DReqAddrPre.v
../../../RTL/DBus/DReqDataPre.v
../../../RTL/DBus/DReqArbiter.v
../../../RTL/DBus/DBus.v
../../../RTL/DBus/DRespDataPre.v
../../../RTL/CSU/CSU.v
../../../RTL/Mem/IM_RFM.v
../../../RTL/Mem/MIM.v
../../../RTL/Mem/DM.v
../../../RTL/Mem/DM_less.v
../../../RTL/ASSIST/MIMMem_N.v
../../../RTL/ASSIST/WAdapter.v
../../../RTL/ASSIST/SingleRAM4096_128_RFM.v
../../../RTL/ASSIST/SingleRAM4096_128.v
../../../RTL/ASSIST/SingleRAM4096.v
../../../RTL/ASSIST/SingleRAM2048_16.v
../../../RTL/ASSIST/WaitUnit.v
../../../RTL/ASSIST/AXIAdapter.v
../../../RTL/ASSIST/AXIWAdapter.v
../../../RTL/ASSIST/IBus.v
../../../RTL/ASSIST/ASFIFO.v
../../../RTL/ASSIST/SMAdapter.v
../../../RTL/ASSIST/DBBus.v
../../../RTL/ASSIST/SingleRAM128_128.v
../../../RTL/ASSIST/SingleRAM256_128.v
../../../RTL/ASSIST/SingleRAM512_128.v
../../../RTL/CSU/SendFIFO.v
../../../RTL/CSU/DMAController.v
../../../RTL/CSU/LogFIFO.v
../../../RTL/CSU/WriteBuffer.v
../../../RTL/CSU/SFIFO.v
../../../RTL/CSU/CmdFIFO.v
../../../RTL/CSU/InDataLatch.v
../../../RTL/CSU/MailBox.v
../../../RTL/CSU/OutDataLatch.v
../../../RTL/CSU/RFMem.v
../../../RTL/CSU/VX1Mem.v

../../../RTL/Lib/sadels0c4l1p4096x128m4b4w1c1p0d0t1s2sdz1rw01_fast_func.v
../../../RTL/Lib/sacrls0c4l1p2048x128m4b2w1c1p0d0t1s2z1rw00.v
../../../RTL/Lib/sacrls0c4l1p2048x16m4b2w1c0p0d0t1s2z1rw00.v
../../../RTL/Lib/sadrls0c4l2p64x14m2b1w0c0p0d0t1s2z1rw00.v
../../../RTL/Lib/sadrls0c4l2p64x22m2b1w0c0p0d0t1s2z1rw00.v
../../../RTL/Lib/sadrls0c4l2p64x26m2b1w0c0p0d0t1s2z1rw00.v
../../../RTL/Lib/sadrls0c4l2p64x38m2b1w0c0p0d0t1s2z1rw00.v
../../../RTL/Lib/sadels0c4s1p128x32m4b1w0c0p0d0t1s2sdz1rw01.v
../../../RTL/Lib/sadels0c4s1p256x32m4b1w0c0p0d0t1s2sdz1rw01.v
../../../RTL/Lib/sadels0c4s1p512x32m4b1w0c0p0d0t1s2sdz1rw01.v
../../../RTL/Lib/sacrls0c4l1p256x128m1b1w1c0p0d0t1s2z1rw00.v
../../../RTL/Lib/sacrls0c4l1p2048x32m4b2w0c0p0d0t1s2z1rw00.v
../../../RTL/Lib/sadcls0c4l1p4096x128m4b4w1c1p0d0t1s2sdz1rw00.v
../../../RTL/Lib/cklnqd8bwp7d5t16p96cpdlvt.v

-v ../../../RTL/Lib/ts16ncpllogl16hsh090f.v
-v ../../../RTL/Lib/ts16ncpllogl16hsl090f.v
-v ../../../RTL/Lib/std_cells.v

